spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
#spring:
#  config:
#    activate:
#      on-profile:
#        - test
#  mongodb:
#    embedded:
#      version: latest
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: local
